##############################################################
# Learning Module: Vagrant Up for Network Envineers
# Lab: Using the Ansible Provisioner with Vagrant
# Author: Hank Preston <hapresto@cisco.com>
#
# ansible_provision.yaml
# Illustrate the following concepts:
# - Basic Playbook Structure for NX-OS Modules
# - Customizations to support Vagrant Devices
##############################################################
---
- name: Provision IOS-XE Devices
  hosts: sw
  connection: local
  gather_facts: false

  tasks:
    - name: Pause to complete boot
      pause:
        seconds: 2

    - name: Configure System Settings
      ios_system:
        hostname: "{{inventory_hostname}}"
        domain_name: test.example.com
        provider: "{{provider_ssh}}"

    - name: Generic Config
      ios_config:
        provider: "{{provider_ssh}}"
        lines:
          - ip scp server enable
          - interface {{item.name}}
          - description {{item.desc}}
          - ip address {{item.ip_address}} {{item.subnet_mask}}
          - no shut
      loop: "{{ interfaces }}"

#    - name: Configure Interfaces
#      with_items: "{{ interfaces }}"
#      nxos_interface:
#        provider: "{{provider_nxapi}}"
#        interface: "{{ item.name }}"
#        mode: layer3
#        description: "{{ item.desc }}"
#        admin_state: up
#
#    - name: Configure IPv4 Address on Interface
#      with_items: "{{ interfaces }}"
#      nxos_ip_interface:
#        provider: "{{provider_nxapi}}"
#        interface: "{{ item.name }}"
#        version: v4
#        addr: "{{ item.ip_address }}"
#        mask: "{{ item.prefix }}"
